### ISSUE TITLE
Not showing less than 3 perc

### ISSUE THREAD

**Issue by Arulanand-Dev** [IgniteUI/marketing-dashboard-sample#1]
![image](https://user-images.githubusercontent.com/61261809/100650270-b23f2f00-3369-11eb-8025-0b20d7a13239.png)
[](url)

**Comment by gmurray81** [comment]
Hi, by default small values get rolled into the "Others" slice. To control the threshold at which this occurs, you can use `othersCategoryThreshold`, and `othersCategoryType`
